service: create-order
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 6000
    lambdaPort: 6002

functions:
  app:
    handler: src/handler.handler
    events:
      - http:
          method: POST
          path: /create-order
