service: admin-back-order-core
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 6000
    lambdaPort: 6002

functions:
  app:
    handler: src/handler.handler
    timeout: 12
    events:
      - http:
          method: POST
          path: /create-order
