export const validateStatusChange = (currentStatus: string, toStatus: string) => {
  const statusChangeMap: Record<string, string[]> = {
    VALIDANDO_RECETA: ['EN_OBSERVACION', 'OBSERVACIONES_RECETAS', 'CREADO', 'VALIDANDO_RECETA'],
    RECETA_VALIDADA: ['VALIDANDO_RECETA', 'CREADO', 'EN_OBSERVACION', 'RECETA_VALIDADA'],
    OBSERVACIONES_RECETAS: ['CREADO', 'EN_OBSERVACION', 'OBSERVACIONES_RECETAS'],
    PREPARANDO: ['RECETA_VALIDADA', 'PREPARANDO'],
    LISTO_PARA_RETIRO: ['PREPARANDO', 'LISTO_PARA_RETIRO'],
    ASIGNAR_A_DELIVERY: ['PREPARANDO', 'ASIGNAR_A_DELIVERY'],
    EN_DELIVERY: ['ASIGNAR_A_DELIVERY', 'EN_DELIVERY'],
    ENTREGADO: ['LISTO_PARA_RETIRO', 'EN_DELIVERY', 'ENTREGADO'],
    EN_OBSERVACION: ['VALIDANDO_RECETA', 'OBSERVACIONES_RECETAS', 'PREPARANDO', 'EN_OBSERVACION'],
    CANCELADO: ['VALIDANDO_RECETA', 'OBSERVACIONES_RECETAS', 'EN_OBSERVACION', 'CANCELADO'],
    CREADO: [],
  };

  const nextValidStatus: string[] = statusChangeMap[toStatus];

  if (nextValidStatus?.includes(currentStatus)) {
    return true;
  } else {
    return false;
  }
};
